dist: xenial
services:
  - xvfb
cache: apt
language: python
sudo: false
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
python:
  - 3.6
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - python --version
  - which python
  - pip --version
  # coveralls requires coverage==4.0.3, recent versions of pytest-cov require coverage>=4.4
  - travis_retry conda install numpy --yes
  - travis_retry conda install pytorch torchvision -c pytorch --yes
  - travis_retry conda install nibabel -c conda-forge --yes
  - travis_retry pip install coverage nose pytest-pep8 pytest-cov coveralls
  - travis_retry python setup.py install
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=niftidataset tests
after_success:
  - coveralls
